# Dockerfile for cross compiling rqbit binaries from scratch inside docker.
FROM --platform=$BUILDPLATFORM tonistiigi/xx@sha256:c64defb9ed5a91eacb37f96ccc3d4cd72521c4bd18d5442905b95e2226b0e707 AS xx

FROM --platform=$BUILDPLATFORM rust:alpine@sha256:1716b3aa042d735f4566d14dc54e8037de9d69556e2d5dd58131d93a613d173d AS builder
COPY --from=xx / /

RUN apk update && apk add ca-certificates clang lld npm pkgconf

ARG TARGETPLATFORM
RUN xx-apk add gcc musl-dev openssl-dev openssl-libs-static

COPY / /src/
WORKDIR /src/

ENV PROFILE_NAME=release-github
ENV PROFILE_FOLDER=release-github

RUN --mount=type=cache,target=/usr/local/cargo/git/db \
    --mount=type=cache,target=/usr/local/cargo/registry/cache \
    --mount=type=cache,target=/usr/local/cargo/registry/index \
    --mount=type=cache,target=/src/target <<EOF
set -e
export TT="$(xx-cargo --print-target-triple)"
export BIN="./target/${TT}/${TT}/${PROFILE_FOLDER}/rqbit"
export OPENSSL_STATIC=1

find /src/target \
        /usr/local/cargo/git/db \
        /usr/local/cargo/registry/cache \
        /usr/local/cargo/registry/index \
        -maxdepth 2 -type d
xx-cargo build \
    --target-dir "target/${TT}" \
    --profile "${PROFILE_NAME}"
find /src/target -maxdepth 4 -type d
xx-verify --static "${BIN}"
mv "${BIN}" /bin/rqbit
EOF

FROM scratch

COPY --from=builder /bin/rqbit /rqbit
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /cacert.pem
